# Generated by Django 5.2.5 on 2025-09-04 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.university'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.course'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.course'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.semester'),
        ),
        migrations.AlterField(
            model_name='ugnote',
            name='pdf_file',
            field=models.FileField(upload_to='notes/pdfs/'),
        ),
        migrations.AlterField(
            model_name='ugnote',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.subject'),
        ),
        migrations.AlterField(
            model_name='ugnote',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='university',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.state'),
        ),
        migrations.DeleteModel(
            name='UGPYQ',
        ),
    ]
